# Generated by Django 4.1 on 2023-08-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='api/static/images/default.jpg', upload_to='profile-img'),
        ),
    ]
