# Generated by Django 4.1 on 2023-09-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
