# Generated by Django 4.1 on 2023-09-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user'),
        ('users', '0010_initial'),
    ]

    operations = [
    ]
