# Generated by Django 4.1 on 2023-09-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_0007_user_0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userid',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
